import './globals.css';

import { SpeedInsights } from '@vercel/speed-insights/next';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

import Footer from '@/components/common/footer';
import { Toaster } from '@/components/ui/sonner';
import { CartStoreProvider } from '@/hooks/cart-store';
import ReactQueryProvider from '@/providers/react-query';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'MIRASWEAR',
  description: 'Generated by MIRASWEAR',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} flex min-h-screen flex-col antialiased`}
      >
        <ReactQueryProvider>
          <CartStoreProvider>
            <main className="flex-1">
              {children}
              <SpeedInsights />
            </main>
          </CartStoreProvider>
        </ReactQueryProvider>
        <Toaster position="top-center" />
        <Footer />
      </body>
    </html>
  );
}
